# Generated by Django 4.0.4 on 2022-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='normalized',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='preprocessed',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='sentimen',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
                ('label', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='stemmed',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='stopwords',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='tokenize',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(max_length=2000)),
                ('created_at', models.DateField()),
                ('username', models.CharField(default='user', max_length=200)),
            ],
        ),
    ]
