# Generated by Django 4.0.4 on 2022-07-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preprocessed',
        ),
    ]
