# Generated by Django 4.0.4 on 2022-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_delete_preprocessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimen',
            name='label',
            field=models.CharField(choices=[('-1', 'Negatif'), ('0', 'Netral'), ('1', 'Positif')], default=None, max_length=10, null=True),
        ),
    ]
