# Generated by Django 4.0.4 on 2022-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_alter_sentimen_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimen',
            name='label',
            field=models.CharField(default='0', max_length=2000),
        ),
    ]
