# Generated by Django 4.0.4 on 2022-08-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0004_alter_sentimen_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimen',
            name='vector',
            field=models.CharField(default='0', max_length=10000),
        ),
    ]
