# Generated by Django 4.0.4 on 2022-08-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0007_sentimen_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentimen',
            name='vector',
        ),
    ]
