# Generated by Django 4.0.4 on 2022-08-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0008_remove_sentimen_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='taken',
            field=models.CharField(default='first', max_length=200),
        ),
    ]
