# Generated by Django 4.0.4 on 2022-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0009_tweet_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='sesi',
            fields=[
                ('sesi_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
