# Generated by Django 4.0.4 on 2022-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0010_sesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimen',
            name='taken',
            field=models.CharField(default='first', max_length=200),
        ),
    ]
