# Generated by Django 4.0.4 on 2022-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0012_df_idf_tf_tfidf'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalized',
            name='sess',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='stemmed',
            name='sess',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='stopwords',
            name='sess',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='tokenize',
            name='sess',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
