# Generated by Django 4.0.4 on 2022-10-09 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0014_delete_df_delete_idf_delete_tf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimen',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
