# Generated by Django 4.0.4 on 2022-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0015_sentimen_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_test',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tfidf', models.CharField(default='0', max_length=2000)),
                ('label', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='data_train',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tfidf', models.CharField(default='0', max_length=2000)),
                ('label', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='sesi',
        ),
    ]
