# Generated by Django 4.0.4 on 2022-10-20 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0020_alter_data_test_tweet_vec_alter_data_train_tweet_vec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_test',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 9, 55, 21, 460763, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='data_train',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 9, 55, 21, 460763, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='vector',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 9, 55, 21, 460763, tzinfo=utc)),
        ),
    ]
