# Generated by Django 4.0.4 on 2022-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0021_data_test_created_at_data_train_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='latih',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
                ('created_at', models.DateField(default='null')),
                ('label', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='uji',
            fields=[
                ('tweet_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(default='0', max_length=2000)),
                ('created_at', models.DateField(default='null')),
                ('label', models.CharField(default='0', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='data_test',
        ),
        migrations.DeleteModel(
            name='data_train',
        ),
        migrations.DeleteModel(
            name='tfidf',
        ),
        migrations.DeleteModel(
            name='vector',
        ),
    ]
