# Generated by Django 4.0.4 on 2022-10-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0022_latih_uji_delete_data_test_delete_data_train_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stopwords',
            new_name='stopworded',
        ),
    ]
